# Generated by Django 4.2.2 on 2023-06-08 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+237690407052",
                        max_length=30,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "about_me",
                    models.TextField(
                        default="Tells us more about you", verbose_name="About Me"
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Real estate license",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                        verbose_name="gender of user",
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        default="/profile.png",
                        upload_to="",
                        verbose_name=" user avatar",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="CMR",
                        help_text="the country of this user",
                        max_length=2,
                        verbose_name="User Country",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Douala",
                        max_length=200,
                        verbose_name="city of the user",
                    ),
                ),
                (
                    "is_buyer",
                    models.CharField(
                        default=False,
                        help_text="Are you looking for buying houses",
                        verbose_name="Buyer",
                    ),
                ),
                (
                    "is_agent",
                    models.BooleanField(
                        default=False,
                        help_text="Are you looking for selling houses",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "top_agent",
                    models.BooleanField(
                        default=False,
                        help_text="Are you a top agent",
                        verbose_name="Top Agent",
                    ),
                ),
                (
                    "ratings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "num_reviews",
                    models.IntegerField(default=0, verbose_name="number of reviews"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
